# Upstream 블록 구성
upstream backend_cluster {
    east_conn;  # Least Connections: 연결 수가 가장 적은 서버로 전달하려면 아래 주석 해제
    ip_hash; # IP Hash: 클라이언트 IP를 해싱하여 항상 같은 서버로 전달하려면 아래 주석 해제
    server backend:8080;
}

server {
    listen 80;
    server_name localhost;

    location ^~ /api/sse {
        proxy_pass http://backend_cluster/api/sse;

        # 실제 요청을 처리한 백엔드 컨테이너의 IP를 응답 헤더에 추가
        add_header X-Upstream-Server $upstream_addr always;

        # SSE를 위한 헤더
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

    location ^~ /api/ {
        proxy_pass http://backend_cluster/api/;
        add_header X-Upstream-Server $upstream_addr always;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /ws/ {
        proxy_pass http://backend_cluster/ws/;
        add_header X-Upstream-Server $upstream_addr always;

        # WebSocket을 위한 헤더
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}