server:
  port: 0 # 여기 바꿔야함

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    hikari:
      connection-init-sql: "schema.sql"

# 초기 데이터 필요하면 만들어서 쓰기
#    sql:
#      init:
#        mode: always
#        schema-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: info