spring:
  application:
    name: discodeit
  servlet:
    multipart:
      enabled: true               # 파일 업로드 활성화 여부 (기본값 true)
      max-file-size: 10MB         # 업로드 가능한 개별 파일 최대 크기
      max-request-size: 20MB      # 전체 요청의 최대 크기
      location: /tmp
  # DB 접속 정보
  datasource:
#    url: jdbc:postgresql://localhost:5432/discodeit?currentSchema=discodeit
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true
  # JPA 설정
  jpa:
    generate-ddl: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    OSIV 비활성화
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    # 실행되는 SQL 출력
    org.hibernate.SQL: debug
    # 바인딩되는 파라미터 출력
    org.hibernate.orm.jdbc.bind: trace

#discodeit:
#  repository:
#    type: file   # jcf | file
#    file-directory: .discodeit

discodeit:
  storage:
    local:
      root-path: ./storage

# 3. server config
server:
  port: 8080