spring:
  application:
    name: discodeit

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}  # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
      s3:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
        region: ${AWS_S3_REGION}
        bucket: ${AWS_S3_BUCKET}
        presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: 황진서의 코드잇 과제
    version: 1.7.0
    spring-boot-version: 3.4.0
    java-version: ${java.version}

  datasource:
    url: ${spring.datasource.url:}
    driver-class-name: ${spring.datasource.driver-class-name:}

  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto:}

  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}

  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}

file:
  upload-dir: build/resources/main/static/images/